# Generated by Django 6.0.4 on 2026-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=100)),
                ('analysis_type', models.CharField(choices=[('fully_analysis', 'Fully Analysis'), ('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('risk', 'Risk Analysis'), ('technical', 'Technical Analysis')], max_length=50)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('stock_symbol', 'analysis_type')},
            },
        ),
    ]
