# Generated by Django 6.0.4 on 2026-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_aianalysisrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='request_analysis_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='request_filter_growth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='request_filter_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='request_filter_mid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='request_filter_penny',
            field=models.BooleanField(default=False),
        ),
    ]
