# Generated by Django 6.0.4 on 2026-05-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_contactrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='premium_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
