# Generated by Django 6.0.4 on 2026-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_users_premium_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='ai_analysis_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='ai_analysis_remaining',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='ai_analysis_used',
            field=models.IntegerField(default=0),
        ),
    ]
