# Generated by Django 6.0.4 on 2026-05-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_contactrequest_ai_analysis_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='requested_features',
        ),
        migrations.RemoveField(
            model_name='users',
            name='allowed_features',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='requested_analysis_count',
        ),
        migrations.AddField(
            model_name='users',
            name='feature_analysis_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='feature_filter_growth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='feature_filter_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='feature_filter_mid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='feature_filter_penny',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
