# Generated by Django 6.0.4 on 2026-05-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_users_first_name_remove_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ai_analysis_daily_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='users',
            name='ai_analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='ai_analysis_used_today',
            field=models.IntegerField(default=0),
        ),
    ]
